//$(document).ready(function() {
//
//	
//
//
//
//	
//});

var jsonContent = {
        "featured": [
         "The birch canoe slid on the smooth planks.",
        "Glue the sheet to the dark blue background.",
        "It's easy to tell the depth of a well.",
        "These days a chicken leg is a rare dish.",
        "Rice is often served in round bowls.",
        "The juice of lemons makes fine punch.",
        "The box was thrown beside the parked truck.",
        "The hogs were fed chopped corn and garbage.",
        "Four hours of steady work faced us.",
        "Large size in stockings is hard to sell.",
        "The boy was there when the sun rose.",
        "A rod is used to catch pink salmon.",
        "The source of the huge river is the clear spring.",
        "Kick the ball straight and follow through.",
        "Help the woman get back to her feet.",
        "A pot of tea helps to pass the evening.",
        "Smoky fires lack flame and heat.",
        "The soft cushion broke the man's fall.",
        "The salt breeze came across from the sea.",
        "The girl at the booth sold fifty bonds.",
        "The small pup gnawed a hole in the sock.",
        "The fish twisted and turned on the bent hook.",
        "Press the pants and sew a button on the vest.",
        "The swan dive was far short of perfect.",
        "The beauty of the view stunned the young boy.",
        "Two blue fish swam in the tank.",
        "Her purse was full of useless trash.",
        "The colt reared and threw the tall rider.",
        "It snowed, rained, and hailed the same morning.",
        "Read verse out loud for pleasure.",
        "Hoist the load to your left shoulder.",
        "Take the winding path to reach the lake.",
        "Note closely the size of the gas tank.",
        "Wipe the grease off his dirty face.",
        "Mend the coat before you go out.",
        "The wrist was badly strained and hung limp.",
        "The stray cat gave birth to kittens.",
        "The young girl gave no clear response.",
        "The meal was cooked before the bell rang.",
        "What joy there is in living.",
        "A king ruled the state in the early days.",
        "The ship was torn apart on the sharp reef.",
        "Sickness kept him home the third week.",
        "The wide road shimmered in the hot sun.",
        "The lazy cow lay in the cool grass.",
        "Lift the square stone over the fence.",
        "The rope will bind the seven books at once.",
        "Hop over the fence and plunge in.",
        "The friendly gang left the drug store.",
        "Mesh mire keeps chicks inside.",
        "The frosty air passed through the coat.",
        "The crooked maze failed to fool the mouse.",
        "Adding fast leads to wrong sums.",
        "The show was a flop from the very start.",
        "A saw is a tool used for making boards.",
        "The wagon moved on well oiled wheels.",
        "March the soldiers past the next hill.",
        "A cup of sugar makes sweet fudge.",
        "Place a rosebush near the porch steps.",
        "Both lost their lives in the raging storm.",
        "We talked of the slide show in the circus.",
        "Use a pencil to write the first draft.",
        "He ran half way to the hardware store.",
        "The clock struck to mark the third period.",
        "A small creek cut across the field.",
        "Cars and busses stalled in snow drifts.",
        "The set of china hit, the floor with a crash.",
        "This is a grand season for hikes on the road.",
        "The dune rose from the edge of the water.",
        "Those words were the cue for the actor to leave.",
        "A yacht slid around the point into the bay.",
        "The two met while playing on the sand.",
        "The ink stain dried on the finished page.",
        "The walled town was seized without a fight.",
        "The lease ran out in sixteen weeks.",
        "A tame squirrel makes a nice pet.",
        "The horn of the car woke the sleeping cop.",
        "The heart beat strongly and with firm strokes.",
        "The pearl was worn in a thin silver ring.",
        "The fruit peel was cut in thick slices.",
        "The Navy attacked the big task force.",
        "See the cat glaring at the scared mouse.",
        "There are more than two factors here.",
        "The hat brim was wide and too droopy.",
        "The lawyer tried to lose his case.",
        "The grass curled around the fence post.",
        "Cut the pie into large parts.",
        "Men strive but seldom get rich.",
        "Always close the barn door tight.",
        "He lay prone and hardly moved a limb.",
        "The slush lay deep along the street.",
        "A wisp of cloud hung in the blue air.",
        "A pound of sugar costs more than eggs.",
        "The fin was sharp and cut the clear water.",
        "The play seems dull and quite stupid.",
        "Bail the boat, to stop it from sinking.",
        "The term ended in late June that year.",
        "A tusk is used to make costly gifts.",
        "Ten pins were set in order.",
        "The bill as paid every third week.",
        "Oak is strong and also gives shade.",
        "Cats and dogs each hate the other.",
        "The pipe began to rust while new.",
        "Open the crate but don't break the glass.",
        "Add the sum to the product of these three.",
        "Thieves who rob friends deserve jail.",
        "The ripe taste of cheese improves with age.",
        "Act on these orders with great speed.",
        "The hog crawled under the high fence.",
        "Move the vat over the hot fire.",
        "The bark of the pine tree was shiny and dark.",
        "Leaves turn brown and yellow in the fall.",
        "The pennant waved when the wind blew.",
        "Split the log with a quick, sharp blow.",
        "Burn peat after the logs give out.",
        "He ordered peach pie with ice cream.",
        "Weave the carpet on the right hand side.",
        "Hemp is a weed found in parts of the tropics.",
        "A lame back kept his score low.",
        "We find joy in the simplest things.",
        "Type out three lists of orders.",
        "The harder he tried the less he got done.",
        "The boss ran the show with a watchful eye.",
        "The cup cracked and spilled its contents.",
        "Paste can cleanse the most dirty brass.",
        "The slang word for raw whiskey is booze.",
        "It caught its hind paw in a rusty trap.",
        "The wharf could be seen at the farther shore.",
        "Feel the heat of the weak dying flame.",
        "The tiny girl took off her hat.",
        "A cramp is no small danger on a swim.",
        "He said the same phrase thirty times.",
        "Pluck the bright rose without leaves.",
        "Two plus seven is less than ten.",
        "The glow deepened in the eyes of the sweet girl.",
        "Bring your problems to the wise chief.",
        "Write a fond note to the friend you cherish.",
        "Clothes and lodging are free to new men.",
        "We frown when events take a bad turn.",
        "Port is a strong wine with s smoky taste.",
        "The young kid jumped the rusty gate.",
        "Guess the results from the first scores.",
        "A salt pickle tastes fine with ham.",
        "The just claim got the right verdict.",
        "These thistles bend in a high wind.",
        "Pure bred poodles have curls.",
        "The tree top waved in a graceful way.",
        "The spot on the blotter was made by green ink.",
        "Mud was spattered on the front of his white shirt.",
        "The cigar burned a hole in the desk top.",
        "The empty flask stood on the tin tray.",
        "A speedy man can beat this track mark.",
        "He broke a new shoelace that day.",
        "The coffee stand is too high for the couch.",
        "The urge to write short stories is rare.",
        "The pencils have all been used.",
        "The pirates seized the crew of the lost ship.",
        "We tried to replace the coin but failed.",
        "She sewed the torn coat quite neatly.",
        "The sofa cushion is red and of light weight.",
        "The jacket hung on the back of the wide chair.",
        "At that high level the air is pure.",
        "Drop the two when you add the figures.",
        "A filing case is now hard to buy.",
        "An abrupt start does not win the prize.",
        "Wood is best for making toys and blocks.",
        "The office paint was a dull sad tan.",
        "He knew the skill of the great young actress.",
        "A rag will soak up spilled water.",
        "A shower of dirt fell from the hot pipes.",
        "Steam hissed from the broken valve.",
        "The child almost hurt the small dog.",
        "There was a sound of dry leaves outside.",
        "The sky that morning was clear and bright blue.",
        "Torn scraps littered the stone floor.",
        "Sunday is the best part of the week.",
        "The doctor cured him with these pills.",
        "The new girl was fired today at noon.",
        "They felt gay when the ship arrived in port.",
        "Add the store's account to the last cent.",
        "Acid burns holes in wool cloth.",
        "Fairy tales should be fun to write.",
        "Eight miles of woodland burned to waste.",
        "The third act was dull and tired the players.",
        "A young child should not suffer fright.",
        "Add the column and put the sum here.",
        "We admire and love a good cook.",
        "There the flood mark is ten inches.",
        "He carved a head from the round block of marble.",
        "She has st smart way of wearing clothes.",
        "The fruit of a fig tree is apple-shaped.",
        "Corn cobs can be used to kindle a fire.",
        "Where were they when the noise started.",
        "The paper box is full of thumb tacks.",
        "Sell your gift to a buyer at a good gain.",
        "The tongs lay beside the ice pail.",
        "The petals fall with the next puff of wind.",
        "Bring your best compass to the third class.",
        "They could laugh although they were sad.",
        "Farmers came in to thresh the oat crop.",
        "The brown house was on fire to the attic.",
        "The lure is used to catch trout and flounder.",
        "Float the soap on top of the bath water.",
        "A blue crane is a tall wading bird.",
        "A fresh start will work such wonders.",
        "The club rented the rink for the fifth night.",
        "After the dance they went straight home.",
        "The hostess taught the new maid to serve.",
        "He wrote his last novel there at the inn.",
        "Even the worst will beat his low score.",
        "The cement had dried when he moved it.",
        "The loss of the second ship was hard to take.",
        "The fly made its way along the wall.",
        "Do that with a wooden stick.",
        "Lire wires should be kept covered.",
        "The large house had hot water taps.",
        "It is hard to erase blue or red ink.",
        "Write at once or you may forget it.",
        "The doorknob was made of bright clean brass.",
        "The wreck occurred by the bank on Main Street.",
        "A pencil with black lead writes best.",
        "Coax a young calf to drink from a bucket.",
        "Schools for ladies teach charm and grace.",
        "The lamp shone with a steady green flame.",
        "They took the axe and the saw to the forest.",
        "The ancient coin was quite dull and worn.",
        "The shaky barn fell with a loud crash.",
        "Jazz and swing fans like fast music.",
        "Rake the rubbish up and then burn it.",
        "Slash the gold cloth into fine ribbons.",
        "Try to have the court decide the case.",
        "They are pushed back each time they attack.",
        "He broke his ties with groups of former friends.",
        "They floated on the raft to sun their white backs.",
        "The map had an X that meant nothing.",
        "Whitings are small fish caught in nets.",
        "Some ads serve to cheat buyers.",
        "Jerk the rope and the bell rings weakly.",
        "A waxed floor makes us lose balance.",
        "Madam, this is the best brand of corn.",
        "On the islands the sea breeze is soft and mild.",
        "The play began as soon as we sat down.",
        "This will lead the world to more sound and fury",
        "Add salt before you fry the egg.",
        "The rush for funds reached its peak Tuesday.",
        "The birch looked stark white and lonesome.",
        "The box is held by a bright red snapper.",
        "To make pure ice, you freeze water.",
        "The first worm gets snapped early.",
        "Jump the fence and hurry up the bank.",
        "Yell and clap as the curtain slides back.",
        "They are men who walk the middle of the road.",
        "Both brothers wear the same size.",
        "In some form or other we need fun.",
        "The prince ordered his head chopped off.",
        "The houses are built of red clay bricks.",
        "Ducks fly north but lack a compass.",
        "Fruit flavors are used in fizz drinks.",
        "These pills do less good than others.",
        "Canned pears lack full flavor.",
        "The dark pot hung in the front closet.",
        "Carry the pail to the wall and spill it there.",
        "The train brought our hero to the big town.",
        "We are sure that one war is enough.",
        "Gray paint stretched for miles around.",
        "The rude laugh filled the empty room.",
        "High seats are best for football fans.",
        "Tea served from the brown jug is tasty.",
        "A dash of pepper spoils beef stew.",
        "A zestful food is the hot-cross bun.",
        "The horse trotted around the field at a brisk pace.",
        "Find the twin who stole the pearl necklace.",
        "Cut the cord that binds the box tightly.",
        "The red tape bound the smuggled food.",
        "Look in the corner to find the tan shirt.",
        "The cold drizzle will halt the bond drive.",
        "Nine men were hired to dig the ruins.",
        "The junk yard had a mouldy smell.",
        "The flint sputtered and lit a pine torch.",
        "Soak the cloth and drown the sharp odor.",
        "The shelves were bare of both jam or crackers.",
        "A joy to every child is the swan boat.",
        "All sat frozen and watched the screen.",
        "A cloud of dust stung his tender eyes.",
        "To reach the end he needs much courage.",
        "Shape the clay gently into block form.",
        "The ridge on a smooth surface is a bump or flaw.",
        "Hedge apples may stain your hands green.",
        "Quench your thirst, then eat the crackers.",
        "Tight curls get limp on rainy days.",
        "The mute muffled the high tones of the horn.",
        "The gold ring fits only a pierced ear.",
        "The old pan was covered with hard fudge.",
        "Watch the log float in the wide river.",
        "The node on the stalk of wheat grew daily.",
        "The heap of fallen leaves was set on fire.",
        "Write fast, if you want to finish early.",
        "His shirt was clean but one button was gone.",
        "The barrel of beer was a brew of malt and hops.",
        "Tin cans are absent from store shelves.",
        "Slide the box into that empty space.",
        "The plant grew large and green in the window.",
        "The beam dropped down on the workmen's head.",
        "Pink clouds floated with the breeze.",
        "She danced like a swan, tall and graceful.",
        "The tube was blown and the tire flat and useless.",
        "It is late morning on the old wall clock.",
        "Let's all join as we sing the last chorus.",
        "The last switch cannot be turned off.",
        "The fight will end in just six minutes.",
        "The store walls were lined with colored frocks.",
        "The peace league met to discuss their plans.",
        "The rise to fame of a person takes luck.",
        "Paper is scarce, so write with much care.",
        "The quick fox jumped on the sleeping cat.",
        "The nozzle of the fire hose was bright brass.",
        "Screw the round cap on as tight as needed.",
        "Time brings us many changes.",
        "The purple tie was ten years old.",
        "Men think and plan and sometimes act.",
        "Fill the ink jar with sticky glue.",
        "He smoke a big pipe with strong contents.",
        "We need grain to keep our mules healthy.",
        "Pack the records in a neat thin case.",
        "The crunch of feet in the snow was the only sound.",
        "The copper bowl shone in the sun's rays.",
        "Boards will warp unless kept dry.",
        "The plush chair leaned against the wall.",
        "Glass will clink when struck by metal.",
        "Bathe and relax in the cool green grass.",
        "Nine rows of soldiers stood in line.",
        "The beach is dry and shallow at low tide.",
        "The idea is to sew both edges straight.",
        "The kitten chased the dog down the street.",
        "Pages bound in cloth make a book.",
        "Try to trace the fine lines of the painting.",
        "Women form less than half of the group.",
        "The zones merge in the central part of town.",
        "A gem in the rough needs work to polish.",
        "Code is used when secrets are sent.",
        "Most of the new is easy for us to hear.",
        "He used the lathe to make brass objects.",
        "The vane on top of the pole revolved in the wind.",
        "Mince pie is a dish served to children.",
        "The clan gathered on each dull night.",
        "Let it burn, it gives us warmth and comfort.",
        "A castle built from sand fails to endure.",
        "A child's wit saved the day for us.",
        "Tack the strip of carpet to the worn floor.",
        "Next Tuesday we must vote.",
        "Pour the stew from the pot into the plate.",
        "Each penny shone like new.",
        "The man went to the woods to gather sticks.",
        "The dirt piles were lines along the road.",
        "The logs fell and tumbled into the clear stream.",
        "Just hoist it up and take it away,",
        "A ripe plum is fit for a king's palate.",
        "Our plans right now are hazy.",
        "Brass rings are sold by these natives.",
        "It takes a good trap to capture a bear.",
        "Feed the white mouse some flower seeds.",
        "The thaw came early and freed the stream.",
        "He took the lead and kept it the whole distance.",
        "The key you designed will fit the lock.",
        "Plead to the council to free the poor thief.",
        "Better hash is made of rare beef.",
        "This plank was made for walking on.",
        "The lake sparkled in the red hot sun.",
        "He crawled with care along the ledge.",
        "Tend the sheep while the dog wanders.",
        "It takes a lot of help to finish these.",
        "Mark the spot with a sign painted red.",
        "Take two shares as a fair profit.",
        "The fur of cats goes by many names.",
        "North winds bring colds and fevers.",
        "He asks no person to vouch for him.",
        "Go now and come here later.",
        "A sash of gold silk will trim her dress.",
        "Soap can wash most dirt away.",
        "That move means the game is over.",
        "He wrote down a long list of items.",
        "A siege will crack the strong defense.",
        "Grape juice and water mix well.",
        "Roads are paved with sticky tar.",
        "Fake &ones shine but cost little.",
        "The drip of the rain made a pleasant sound.",
        "Smoke poured out of every crack.",
        "Serve the hot rum to the tired heroes.",
        "Much of the story makes good sense.",
        "The sun came up to light the eastern sky.",
        "Heave the line over the port side.",
        "A lathe cuts and trims any wood.",
        "It's a dense crowd in two distinct ways.",
        "His hip struck the knee of the next player.",
        "The stale smell of old beer lingers.",
        "The desk was firm on the shaky floor.",
        "It takes heat to bring out the odor.",
        "Beef is scarcer than some lamb.",
        "Raise the sail and steer the ship northward.",
        "The cone costs five cents on Mondays.",
        "A pod is what peas always grow in.",
        "Jerk the dart from the cork target.",
        "No cement will hold hard wood.",
        "We now have a new base for shipping.",
        "The list of names is carved around the base.",
        "The sheep were led home by a dog.",
        "Three for a dime, the young peddler cried.",
        "The sense of smell is better than that of touch.",
        "No hardship seemed to keep him sad.",
        "Grace makes up for lack of beauty.",
        "Nudge gently but wake her now.",
        "The news struck doubt into restless minds.",
        "Once we stood beside the shore.",
        "A chink in the wall allowed a draft to blow.",
        "Fasten two pins on each side.",
        "A cold dip restores health and zest.",
        "He takes the oath of office each March.",
        "The sand drifts over the sill of the old house.",
        "The point of the steel pen was bent and twisted.",
        "There is a lag between thought and act.",
        "Seed is needed to plant the spring corn.",
        "Draw the chart with heavy black lines.",
        "The boy owed his pal thirty cents.",
        "The chap slipped into the crowd and was lost.",
        "Hats are worn to tea and not to dinner.",
        "The ramp led up to the wide highway.",
        "Beat the dust from the rug onto the lawn.",
        "Say it slow!y but make it ring clear.",
        "The straw nest housed five robins.",
        "Screen the porch with woven straw mats.",
        "This horse will nose his way to the finish.",
        "The dry wax protects the deep scratch.",
        "He picked up the dice for a second roll.",
        "These coins will be needed to pay his debt.",
        "The nag pulled the frail cart along.",
        "Twist the valve and release hot steam.",
        "The vamp of the shoe had a gold buckle.",
        "The smell of burned rags itches my nose.",
        "New pants lack cuffs and pockets.",
        "The marsh will freeze when cold enough.",
        "They slice the sausage thin with a knife.",
        "The bloom of the rose lasts a few days.",
        "A gray mare walked before the colt.",
        "Breakfast buns are fine with a hot drink.",
        "Bottles hold four kinds of rum.",
        "The man wore a feather in his felt hat.",
        "He wheeled the bike past the winding road.",
        "Drop the ashes on the worn old rug.",
        "The desk and both chairs were painted tan.",
        "Throw out the used paper cup and plate.",
        "A clean neck means a neat collar.",
        "The couch cover and hall drapes were blue.",
        "The stems of the tall glasses cracked and broke.",
        "The wall phone rang loud and often.",
        "The clothes dried on a thin wooden rack.",
        "Turn on the lantern which gives us light.",
        "The cleat sank deeply into the soft turf.",
        "The bills were mailed promptly on the tenth of the month.",
        "To have is better than to wait and hope.",
        "The price is fair for a good antique clock.",
        "The music played on while they talked.",
        "Dispense with a vest on a day like this.",
        "The bunch of grapes was pressed into wine.",
        "He sent the figs, but kept the ripe cherries.",
        "The hinge on the door creaked with old age.",
        "The screen before the fire kept in the sparks.",
        "Fly by night, and you waste little time.",
        "Thick glasses helped him read the print.",
        "Birth and death mark the limits of life.",
        "The chair looked strong but had no bottom.",
        "The kite flew wildly in the high wind.",
        "A fur muff is stylish once more.",
        "The tin box held priceless stones.",
        "We need an end of all such matter.",
        "The case was puzzling to the old and wise.",
        "The bright lanterns were gay on the dark lawn.",
        "We don't get much money but we have fun.",
        "The youth drove with zest, but little skill.",
        "Five years he lived with a shaggy dog.",
        "A fence cuts through the corner lot.",
        "The way to save money is not to spend much.",
        "Shut the hatch before the waves push it in.",
        "The odor of spring makes young hearts jump.",
        "Crack the walnut with your sharp side teeth.",
        "He offered proof in the form of a large chart.",
        "Send the stuff in a thick paper bag.",
        "A quart of milk is water for the most part.",
        "They told wild tales to frighten him.",
        "The three story house was built of stone.",
        "In the rear of the ground floor was a large passage.",
        "A man in a blue sweater sat at the desk.",
        "Oats are a food eaten by horse and man.",
        "Their eyelids droop for want of sleep.",
        "The sip of tea revives his tired friend.",
        "There are many ways to do these things.",
        "Tuck the sheet under the edge of the mat.",
        "A force equal to that would move the earth.",
        "We like to see clear weather.",
        "The work of the tailor is seen on each side.",
        "Take a chance and win a china doll.",
        "Shake the dust from your shoes, stranger.",
        "She was kind to sick old people.",
        "The dusty bench stood by the stone wall.",
        "The square wooden crate was packed to be shipped.",
        "We dress to suit the weather of most days.",
        "Smile when you say nasty words.",
        "A bowl of rice is free with chicken stew.",
        "The water in this well is a source of good health.",
        "Take shelter in this tent, but keep still.",
        "That guy is the writer of a few banned books.",
        "The little tales they tell are false.",
        "The door was barred, locked, and bolted as well.",
        "Ripe pears are fit for a queen's table.",
        "A big wet stain was on the round carpet.",
        "The kite dipped and swayed, but stayed aloft.",
        "The pleasant hours fly by much too soon.",
        "The room was crowded with a wild mob.",
        "This strong arm shall shield your honor.",
        "She blushed when he gave her a white orchid.",
        "The beetle droned in the hot June sun.",
        "Press the pedal with your left foot.",
        "Neat plans fail without luck.",
        "The black trunk fell from the landing.",
        "The bank pressed for payment of the debt.",
        "The theft of the pearl pin was kept secret.",
        "Shake hands with this friendly child.",
        "The vast space stretched into the far distance.",
        "A rich farm is rare in this sandy waste.",
        "His wide grin earned many friends.",
        "Flax makes a fine brand of paper.",
        "Hurdle the pit with the aid of a long pole.",
        "A strong bid may scare your partner stiff.",
        "Even a just cause needs power to win.",
        "Peep under the tent and see the clowns.",
        "The leaf drifts along with a slow spin.",
        "Cheap clothes are flashy but don't last.",
        "A thing of small note can cause despair.",
        "Flood the mails with requests for this book.",
        "A thick coat of black paint covered all.",
        "The pencil was cut to be sharp at both ends.",
        "Those last words were a strong statement.",
        "He wrote his name boldly at the top of tile sheet.",
        "Dill pickles are sour but taste fine.",
        "Down that road is the way to the grain farmer.",
        "Either mud or dust are found at all times.",
        "The best method is to fix it in place with clips.",
        "If you mumble your speech will be lost.",
        "At night the alarm roused him from a deep sleep.",
        "Read just what the meter says.",
        "Fill your pack with bright trinkets for the poor.",
        "The small red neon lamp went out.",
        "Clams are small, round, soft, and tasty.",
        "The fan whirled its round blades softly.",
        "The line where the edges join was clean.",
        "Breathe deep and smell the piny air.",
        "It matters not if he reads these words or those.",
        "A brown leather bag hung from its strap.",
        "A toad and a frog are hard to tell apart.",
        "A white silk jacket goes with any shoes.",
        "A break in the dam almost caused a flood.",
        "Paint the sockets in the wall dull green.",
        "The child crawled into the dense grass.",
        "Bribes fail where honest men work.",
        "Trample the spark, else the flames will spread.",
        "The hilt of the sword was carved with fine designs.",
        "A round hole was drilled through the thin board.",
        "Footprints showed the path he took up the beach.",
        "She was waiting at my front lawn.",
        "A vent near the edge brought in fresh air.",
        "Prod the old mule with a crooked stick.",
        "It is a band of steel three inches wide.",
        "The pipe ran almost the length of the ditch.",
        "It was hidden from sight by a mass of leaves and shrubs.",
        "The weight of the package was seen on the high scale.",
        "Wake and rise, and step into the green outdoors.",
        "The green light in the brown box flickered.",
        "The brass tube circled the high wall.",
        "The lobes of her ears were pierced to hold rings.",
        "Hold the hammer near the end to drive the nail.",
        "Next Sunday is the twelfth of the month.",
        "Every word and phrase he speaks is true.",
        "He put his last cartridge into the gun and fired.",
        "They took their kids from the public school.",
        "Drive the screw straight into the wood.",
        "Keep the hatch tight and the watch constant.",
        "Sever the twine with a quick snip of the knife.",
        "Paper will dry out when wet.",
        "Slide the catch back and open the desk.",
        "Help the weak to preserve their strength.",
        "A sullen smile gets few friends.",
        "Stop whistling and watch the boys march.",
        "Jerk the cord, and out tumbles the gold.",
        "Slide the tray across the glass top.",
        "The cloud moved in a stately way and was gone.",
        "Light maple makes for a swell room.",
        "Set the piece here and say nothing.",
        "Dull stories make her laugh.",
        "A stiff cord will do to fasten your shoe.",
        "Get the trust fund to the bank early.",
        "Choose between the high road and the low.",
        "A plea for funds seems to come again.",
        "He lent his coat to the tall gaunt stranger.",
        "There is a strong chance it will happen once more.",
        "The duke left the park in a silver coach.",
        "Greet the new guests and leave quickly.",
        "When the frost has come it is time for turkey.",
        "Sweet words work better than fierce.",
        "A thin stripe runs down the middle.",
        "A six comes up more often than a ten.",
        "Lush fern grow on the lofty rocks.",
        "The ram scared the school children off.",
        "The team with the best timing looks good.",
        "The farmer swapped his horse for a brown ox.",
        "Sit on the perch and tell the others what to do.",
        "A steep trail is painful for our feet.",
        "The early phase of life moves fast.",
        "Green moss grows on the northern side.",
        "Tea in thin china has a sweet taste.",
        "Pitch the straw through the door of the stable.",
        "The latch on the beck gate needed a nail.",
        "The goose was brought straight from the old market.",
        "The sink is the thing in which we pile dishes.",
        "A whiff of it will cure the most stubborn cold.",
        "The facts don't always show who is right.",
        "She flaps her cape as she parades the street.",
        "The loss of the cruiser was a blow to the fleet.",
        "Loop the braid to the left and then over.",
        "Plead with the lawyer to drop the lost cause.",
        "Calves thrive on tender spring grass.",
        "Post no bills on this office wall.",
        "Tear a thin sheet from the yellow pad.",
        "A cruise in warm waters in a sleek yacht is fun.",
        "A streak of color ran down the left edge.",
        "It was done before the boy could see it.",
        "Crouch before you jump or miss the mark.",
        "Pack the kits and don't forget the salt.",
        "The square peg will settle in the round hole.",
        "Fine soap saves tender skin.",
        "Poached eggs and tea must suffice.",
        "Bad nerves are jangled by a door slam.",
        "Ship maps are different from those for planes.",
        "Dimes showered down from all sides.",
        "They sang the same tunes at each party.",
        "The sky in the west is tinged with orange red.",
        "The pods of peas ferment in bare fields.",
        "The horse balked and threw the tall rider.",
        "The hitch between the horse and cart broke.",
        "Pile the coal high in the shed corner.",
        "The gold vase is both rare and costly.",
        "The knife was hung inside its bright sheath.",
        "The rarest spice comes from the far East.",
        "The roof should be tilted at a sharp slant.",
        "A smatter of French is worse than none.",
        "The mule trod the treadmill day and night.",
        "The aim of the contest is to raise a great fund.",
        "To send it now in large amounts is bad.",
        "There is a fine hard tang in salty air.",
        "Cod is the main business of the north shore.",
        "The slab was hewn from heavy blocks of slat'e.",
        "Dunk the stale biscuits into strong drink.",
        "Hang tinsel from both branches.",
        "Cap the jar with a tight brass cover.",
        "The poor boy missed the boat again.",
        "Be sure to set the lamp firmly in the hole.",
        "Pick a card and slip it under the pack.",
        "A round mat will cover the dull spot.",
        "The first part of the plan needs changing.",
        "The good book informs of what we ought to know.",
        "The mail comes in three batches per day.",
        "You cannot brew tea in a cold pot.",
        "Dots of light betrayed the black cat.",
        "Put the chart on the mantel and tack it down.",
        "The night shift men rate extra pay.",
        "The red paper brightened the dim stage.",
        "See the player scoot to third base.",
        "Slide the bill between the two leaves.",
        "Many hands help get the job done.",
        "We don't like to admit our small faults.",
        "No doubt about the way the wind blows.",
        "Dig deep in the earth for pirate's gold.",
        "The steady drip is worse than a drenching rain.",
        "A flat pack takes less luggage space.",
        "Green ice frosted the punch bowl.",
        "A stuffed chair slipped from the moving van.",
        "The stitch will serve but needs to be shortened.",
        "A thin book fits in the side pocket.",
        "The gloss on top made it unfit to read.",
        "The hail pattered on the burnt brown grass.",
        "Seven seals were stamped on great sheets.",
        "Our troops are set to strike heavy blows.",
        "The store was jammed before the sale could start.",
        "It was a bad error on the part of the new judge.",
        "One step more and the board will collapse.",
        "Take the match and strike it against your shoe.",
        "The pot boiled, but the contents failed to jell.",
        "The baby puts his right foot in his mouth.",
        "The bombs left most of the town in ruins.",
        "Stop and stare at the hard working man.",
        "The streets are narrow and full of sharp turns.",
        "The pup jerked the leash as he saw a feline shape.",
        "Open your book to the first page.",
        "Fish evade the net, and swim off.",
        "Dip the pail once and let it settle.",
        "Will you please answer that phone.",
        "The big red apple fell to the ground.",
        "The curtain rose and the show was on.",
        "The young prince became heir to the throne.",
        "He sent the boy on a short errand.",
        "Leave now and you will arrive on time.",
        "The corner store was robbed last night.",
        "A gold ring will please most any girl.",
        "The long journey home took a year.",
        "She saw a cat in the neighbor's house.",
        "A pink shell was found on the sandy beach.",
        "Small children came to see him.",
        "The grass and bushes were wet with dew.",
        "The blind man counted his old coins.",
        "A severe storm tore down the barn.",
        "She called his name many times.",
		  "A friend's frown is better than a fool's smile.",
        "A friend in need is a friend indeed.",
        "A friend is easier lost than found.",
        "A friend to everybody is a friend to nobody.",
        "A problem shared is a problem halved.",
        "A true friend is someone who reaches for your hand, but touches your heart.",
        "False friends are worse than open enemies.",
        "Flattery is all right so long as you don't inhale.",
        "Give credit where credit is due.",
        "Grief divided is made lighter.",
        "Memory is the treasure of the mind.",
        "Nothing dries sooner than a tear.",
        "Old friends and old wine are best.",
        "The best of friends must part.",
        "The best things are not bought and sold.",
        "There is no better looking-glass than an old friend.",
        "To err is human (To forgive divine).",
		 "A loveless life is a living death.",
        "Absence makes the heart grow fonder.",
        "All's fair in love and war.",
        "Beauty is in the eye of the beholder.",
        "Before you meet the handsome prince you have to kiss a lot of toads.",
        "Better to have loved and lost, than to have never loved at all.",
        "Cold hands, warm heart.",
        "Distance makes the heart grow fonder.",
        "Faint heart never won fair lady.",
        "First impressions are the most lasting.",
        "Hatred is as blind as love.",
        "Love and a cough cannot be hid.",
        "Love does much but money does all.",
        "Love levels all inequalities.",
        "Love makes a good eye squint.",
        "Love sees no faults.",
        "Love sought is good, but given unsought is better.",
        "Love to live and live to love.",
        "Love with life is heaven; and life unloving, hell.",
        "Man is the head but woman turns it.",
        "Marry in haste, repent at leisure.",
        "The course of love never did run smooth.",
        "The Lord loveth a cheerful liar.",
        "There is a thin line between love and hate.",
        "To eat one's heart out.",
        "True beauty lies within.",
		"A good friend is one's nearest relation.",
        "A man is known by the company he keeps.",
        "A man of straw needs a woman of gold.",
        "A wink is as good as a nod, to a blind man.",
        "An injury is forgiven better than an injury revenged.",
        "Anger and hate hinder good counsel.",
        "Appearances are deceptive.",
        "At a round table there's no dispute about the place.",
        "Attack is the best form of defense.",
        "Be slow in choosing, but slower in changing.",
        "Behind every great man stands a strong woman.",
        "Blood is thicker than water.",
        "Cheerfulness smooths the road of life.",
        "Confess and be hanged.",
        "Conscience makes cowards of us all.",
        "Don't blow your own trumpet.",
        "Do as you would be done by.",
        "Do unto others as you would have them do to you.",
        "Grow angry slowly; there's plenty of time.",
        "He bears misery best that hides it most.",
        "He that hurts another, hurts himself.",
        "He who wronged you will hate you.",
        "Heavy givers are light complainers.",
        "I am rubber and you are glue. Your words bounce off me and stick to you.",
        "If you lose your temper, don't look for it.",
        "It's not over till it's over.",
        "Joy shared is double joy; grief shared is (only) half grief.",
        "Laugh and the world laughs with you. Cry and you cry alone.",
        "Never let the sun set on angry heart.",
        "Never let the sun go down on your anger.",
        "Never let the sun set on thy wrath.",
        "Never quarrel with one's bread and butter.",
        "No man or woman is worth your tears, and the one who is, won't make you cry.",
        "Open confession is good for the soul.",
        "Out of sight, out of mind.",
        "Patience is a virtue.",
        "Persuasion is better than force.",
        "Spare the rod and spoil the child.",
        "Temper is so good a thing that we should never lose it.",
        "To the world you may be one person, but to one person, you may be the world.",
        "Wondrous is the strength of cheerfulness.",
		 "A bully is always a coward.",
        "A handsome shoe often pinches the foot.",
        "A good thing is all the sweeter when won with pain.",
        "A man too careful of danger lives in continual torment.",
        "A miss is as good as a mile.",
        "Adversity flatters no man.",
        "Adversity and loss make a man wise.",
        "All promises are either broken or kept.",
        "All things come to those that wait.",
        "An eye for an eye and a tooth for a tooth.",
        "An open door may tempt a saint.",
        "As one door closes, another always opens.",
        "As you go through life, make this your goal, watch the doughnut and not the hole.",
        "Brevity is the soul of wit.",
        "Cut your coat according to the cloth.",
        "Discretion is the better part of valour.",
        "Do right and fear no man.",
        "Easy come, easy go.",
        "Experience is the hardest teacher. She gives the test first and the lesson afterwards.",
        "Familiarity breeds contempt.",
        "Fortune favours the brave.",
        "He who laughs last, laughs longest.",
        "Home is where the heart is.",
        "Hope for the best and prepare for the worst.",
        "If wishes were horses, beggars would ride.",
        "In the country of the blind, the one-eyed man is king.",
        "It never rains but it pours.",
        "Leave tomorrow till tomorrow.",
        "Life begins at forty.",
        "Lifes trials may be hard to bear, but patience can outlive them.",
        "Live and learn.",
        "Manners maketh the man.",
        "No man is worse for knowing the worst of himself.",
        "Only the good die young.",
        "Procrastination is the thief of time.",
        "The best things in life are free.",
        "The family that prays together, stays together.",
        "The longer you live the more you see.",
        "The meek shall inherit the earth.",
        "The receiver is as bad as the thief.",
        "To wait and be patient soothes many a pang.",
        "Up and down like a fiddler's elbow.",
        "Useless as a screen door on a submarine.",
        "We cannot erase the sad records from our past.",
        "What the eye doesn't see, the heart doesn't grieve over.",
		 "After dinner rest a while, after supper walk a mile.",
        "An apple a day keeps the doctor away.",
        "A drowning man will clutch at a straw.",
        "An onion a day keeps everyone away.",
        "Another pot ! Try the teapot.",
        "As fit as a fiddle.",
        "As hard as nails.",
        "As sick as a dog.",
        "As you go through life, make this your goal, watch the doughnut and not the hole.",
        "Be not a baker if your head is made of butter.",
        "Beauty is but skin deep.",
        "Better late thrive than never do well.",
        "Better to be poor and healthy rather than rich and sick.",
        "Better to wear out than rust out.",
        "Bread never falls but on its buttered side.",
        "Cleanliness is next to Godliness.",
        "Content is health to the sick and riches to the poor.",
        "Don't bite the hand that feeds you.",
        "Drink like a fish, water only.",
        "Early to bed, early to rise, makes you healthy, wealthy & wise.",
        "Fair words butter no cabbage.",
        "Good wine ruins the purse, and bad wine ruins the stomach.",
        "Greediness burst the bag.",
        "Grumbling makes the loaf no larger.",
        "Half a loaf is better than none.",
        "He who drinks a little too much drinks much too much.",
        "He who rises late must trot all day.",
        "His eyes are bigger than his belly.",
        "Hunger is the best sauce.",
        "It is no use crying over spilt milk.",
        "Old friends and old wine are best.",
        "One man's meat is another man's poison.",
        "Ready money is ready medicine.",
        "Sound as a bell.",
        "The nearer the bone the sweeter the meat.",
        "The proof of the pudding is in the eating.",
        "There's many a slip, twixt cup and the lip.",
        "To add insult to injury.",
        "To look as if butter will not melt in his mouth.",
        "Too many cooks spoil the broth.",
        "What can't be cured must be endured.",
        "What you eat today walks and talks tomorrow.",
        "You are what you eat.",
        "You can't have your cake and eat it too.",
        "You can eat an elephant if you do it one mouthful at a time.",
        "You can't unscramble a scrambled egg.",
		  "A fool uttereth all his mind.",
        "A bad excuse is better then none.",
        "Actions speak louder than words.",
        "Angry words fan the fire like wind.",
        "Bad news travels fast.",
        "Call a spade a spade.",
        "Do as I say not as I do.",
        "Don't advertise: Tell it to a gossip.",
        "Don't go off half-cocked.",
        "Few words and many deeds.",
        "For donkeys' ages.",
        "Gossips are frogs, they drink and talk.",
        "He who sings drives away sorrow.",
        "If you don't say it you will not have to unsay it.",
        "It takes two to have an argument.",
        "Keep your mouth shut and your eyes open.",
        "Listen to the pot calling the kettle black.",
        "Many a true word spoken in jest.",
        "No news is good news.",
        "Nothing is ill said if it is not ill taken.",
        "One picture is worth a thousand words.",
        "Say what you mean and mean what you say.",
        "Self praise is no recomendation.",
        "Silence is an excellent remedy against slander.",
        "Silence is golden.",
        "Silence is less injurious than a bad reply.",
        "Since before cocky was an egg.",
        "Speak clearly, if you speak at all.",
        "Sticks and stones may break my bones but words will never hurt me.",
        "Stop beating around the bush.",
        "Take your wife's first advice.",
		 "A change is as good as a rest.",
        "A stitch in time saves nine.",
        "A throne is only a bench covered in purple velvet.",
        "A wise man shall hold his tongue till he sees his opportunity.",
        "Accidents will happen.",
        "All's well that ends well.",
        "Attack is the best means of defence.",
        "Charity begins at home.",
        "Different strokes for different folks.",
        "Do not in an instant what an age cannot recompense.",
        "Don't knock on death's door, ring the doorbell and run.",
        "Don't try to teach your grand-mother to suck eggs.",
        "Empty vessels make the most sound.",
        "Empty barrels make the most noise.",
        "Four eyes are better than two.",
        "He who fights and runs away, lives to fight another day.",
        "Innocent as a new born babe.",
        "It's an ill wind that blows no-one some good.",
        "It is better to stay silent and be thought a fool, than to open one's mouth and remove all doubt.",
        "Necessity is the mother of invention.",
        "No one can be caught in places he does not visit.",
        "No wise man ever wishes to be younger.",
        "Not in a month of Sundays.",
        "One mans junk is another man's treasure.",
        "Out of the frying pan into the fire.",
        "Show a clean pair of heels.",
        "Still waters run deep.",
        "The darkest hour is before the dawn.",
        "The wise shall understand.",
        "Those who don't learn from history are doomed to repeat it.",
        "Tomorrow is a new day.",
        "Two heads are better than one.",
        "You can't tell a book by its cover.",
        "Where observation is concerned, chance favours only the prepared mind.",
        "Where there's smoke there's fire.",
        "Wisdom is better than strength.",
        "Wisdom is neither inheritance nor a legacy.",
        "Wisdom is the wealth of the wise.",
        "Wise it is to comprehend the whole.",
        "You can't put an old head on young shoulders.",
		 "A bad workman blames his tools.",
        "A good reputation is a fair estate.",
        "All work and no play makes Jack a dull boy.",
        "An idle man is the devil's playfellow.",
        "Diligence is the mother of good luck.",
        "Don't try kicking against the wind.",
        "Everybody must row with the oars he has.",
        "Hard work never did anyone any harm.",
        "If a job is worth doing it is worth doing well.",
        "If at first you don't succeed, try, try again.",
        "If you can't help, don't hinder.",
        "If you see something you like, take it and make it better.",
        "It's all in a days work.",
        "Laziness travels so slowly that poverty soon overtakes it.",
        "Least talk most work.",
        "Many hands make light work.",
        "More haste less speed.",
        "Needs must when the devil drives.",
        "Never put off 'til tomorrow what you can do today.",
        "No life can be dreary when work is a delight.",
        "Not to break is better than to mend.",
        "The devil finds work for idle hands.",
        "The harder you work, the luckier you are.",
        "The hardest work is to do nothing.",
		  "A bird in the hand is worth two in the bush.",
        "A bird makes his nest little by little.",
        "A cat has nine lives.",
        "All cats are grey in the dark.",
        "An elephant never forgets.",
        "An old fox need learn no craft.",
        "Birds of a feather flock together.",
        "Curiosity killed the cat; Satisfaction brought it back.",
        "Curses, like chickens come home to roost.",
        "Don't count your chickens before they hatch.",
        "Every dog has its day.",
        "His bark is louder than his bite.",
        "If you lie down with dogs, you'll get up with fleas.",
        "It's an ill bird that fouls its own nest.",
        "It's an old dog for a hard road.",
        "It's no use closing the stable door, after the horse has bolted.",
        "Kill two birds with the one stone.",
        "Let sleeping dogs lie.",
        "Like a fish out of water.",
        "Never look a gift horse in the mouth.",
        "No sense closing the barn door after the horse has bolted.",
        "Nothing falls into the mouth of a sleeping fox.",
        "Putting the cart before the horse.",
        "Sauce for the goose is sauce for the gander.",
        "The early bird catches the worm.",
        "The leopard does not change his spots.",
        "The sleepy fox catches no chickens.",
        "There's no use in flogging a dead horse.",
        "To scare a bird is not the way to catch it.",
        "What do you expect from a pig, but a grunt?",
        "When a fox hears a rabbit screaming it comes running, but not to help.",
        "While the cats away the mice play.",
        "You can lead a horse to water, but you can't make him drink.",
		 "A chain is no stronger than its weakest link.",
        "A rolling stone gathers no moss.",
        "After the storm comes the calm.",
        "All aren't hunters that blow the horn.",
        "As green as grass.",
        "As is the gardener so is the garden.",
        "As you sow, so shall you reap.",
        "Best to bend it while it's a twig.",
        "Better to go back than go wrong.",
        "By hook or by crook.",
        "Deeds are fruits, words are but leaves.",
        "Distance lends enhancement to the view.",
        "Don't count your chickens before they are hatched.",
        "Don't cross your bridges until you come to them.",
        "Empty bags cannot stand upright.",
        "Every cloud has a silver lining.",
        "Every path has its puddle.",
        "Fresh as a daisy.",
        "Good company on the road is the shortest cut.",
        "It is better to be green and growing than ripe and rotten.",
        "Leave no stone unturned.",
        "Like looking for a needle in a haystack.",
        "Make hay while the sun shines.",
        "Milk the cow but don't pull off the udder.",
        "Never cackle unless you lay.",
        "Oaks may fall when reeds take the storm.",
        "Shake the hand before you plough the field.",
        "Strike while the iron's hot.",
        "The beaten path is safest.",
        "The best ground bears weeds as well as flowers.",
        "The grass is always greener on the other side of the fence.",
        "The longest journey begins with the first step.",
        "The longest way round is the sweetest way home.",
        "The more you stir, the more it stinks.",
        "The sun shines on both sides of the hedge.",
        "The worst wheel always creaks most.",
        "Too many irons in the fire.",
		 "A little body doth often harbour a great soul.",
        "A point is the beginning of magnitude.",
        "A spark can start a great fire.",
        "A short cut is often a wrong cut.",
        "Big fish eat little fish.",
        "Everything has an end.",
        "Fall seven times. Stand up eight.",
        "First in best dressed.",
        "From trivial things, great contests often arise.",
        "Give them an inch and they'll take a mile.",
        "Grow angry slowly, there's plenty of time.",
        "He who hesitates is lost.",
        "It's either all or nothing.",
        "It is easier to destroy than to build.",
        "It is the first step that is difficult.",
        "Little strokes fell great oaks.",
        "Lost time is never found again.",
        "Many drops make a shower.",
        "Mighty oaks from tiny acorns grow.",
        "Necessity is a hard nurse, but she raises strong children.",
        "Rome wasn't built in a day.",
        "Seize the day.",
        "Small faults indulged let in greater.",
        "Some of the best gifts come in small packages.",
        "Step by step one goes far.",
		 "A bad penny always comes back.",
        "A light purse makes a heavy heart.",
        "A little each day is much in a year.",
        "A man's intentions seldom add to his income.",
        "A penny saved is a penny earned.",
        "A poor man is better than a liar.",
        "A single penny fairly got is worth a thousand that are not.",
        "Always you are to be rich next year.",
        "Beggars can't be choosers.",
        "Better to have than to wish.",
        "Diamonds are forever.",
        "Every man has his price.",
        "Every man is the architect of his destiny.",
        "Experience is the father of wisdom.",
        "Fair exchange is no robbery.",
        "He has enough who is content.",
        "He that pays last never pays twice.",
        "He is rich that is satisfied.",
        "In for a penny, in for a pound.",
        "It is better to be born lucky than rich.",
        "Little and often fill the purse.",
        "Little thieves are hanged, but great ones escape.",
        "Money burns a hole in your pocket.",
        "Never spend your money before you have it.",
        "One today is worth two tomorrows.",
        "Penny wise, pound foolish.",
        "Take care of the pence and the pounds will take care of themselves.",
        "The best cast at dice is not to play.",
        "The love of money is the root of all evil.",
        "There is no honour among thieves.",
		 "A good conscience is a soft pillow.",
        "A good thing is soon snatched up.",
        "A little knowledge is a dangerous thing.",
        "Better safe than sorry.",
        "Better late than never.",
        "Business before pleasure.",
        "Credit won by lying is quick in dying.",
        "Damage suffered makes you knowing, but seldom rich.",
        "Desperate diseases must have desperate remedies.",
        "Divide and conquer.",
        "Don't rely on the label on the bag.",
        "Don't throw the baby out with the bath-water.",
        "Don't put all your eggs in one basket.",
        "Experience is the best teacher.",
        "First come, first served.",
        "Fore-warned is fore-armed.",
        "Hasty climbers have sudden falls.",
        "Hasty judgements are generally faulty.",
        "Honesty is the best policy.",
        "If anything can go wrong, it will.",
        "If you don't know where you're going, then the journey is never ending.",
        "It's a poor job that can't carry one boss.",
        "Keep It Simple (The KISS principal).",
        "Let the buyer beware.",
        "Look before you leap.",
        "Nobody can serve two masters.",
        "One false move may lose the game.",
        "One man's loss, is another man's gain.",
        "Peace begins just where ambition ends.",
        "Possession is nine tenths of the law.",
        "Rules are made to be broken.",
        "The customer is always right.",
        "The gods help them that help themselves.",
        "The golden age never was the present one.",
        "To each his own.",
        "We do not always gain by changing.",
		"A fool and his money are soon parted.",
        "A fool in a gown is none the wiser.",
        "A wise man doesn't need advice, and a fool won't take it.",
        "Advice when most needed is least heeded.",
        "Always in a hurry, always behind.",
        "Cheap is dear in the long run.",
        "Confess and be hanged.",
        "Cut off one's nose to spite one's face.",
        "Empty vessels make the most noise.",
        "Facts do not cease to exist because they are ignored.",
        "Fools rush in where angels fear to tread.",
        "He who won't be advised, can't be helped.",
        "If the cap fits, wear it.",
        "In one ear and out the other.",
        "It can't happen here is number one on the list of famous last words.",
        "It is better to stay silent and be thought a fool, than to open one's mouth and remove all doubt.",
        "One of these days is none of these days.",
        "Pride cometh before a fall.",
        "Pride feels no pain.",
        "See nothing, say nothing, know nothing.",
        "The bigger they are the harder they fall.",
        "The fool wanders, the wise man travels.",
        "The hood does not make the monk.",
        "The wise man is deceived once but the fool twice.",
        "There is no fool like an old fool.",
        "Use not today what tomorrow will need.",
        "What's the good of home, if you are never in it?",
		    "amazing",
    "awesome",
    "beautiful",
    "bravo",
    "brilliant",
    "breathtaking",
    "congratulations",
    "cool",
    "dazzling",
    "delightful",
    "electrifying",
    "elegant",
    "enchanting",
    "excellent",
    "exciting",
    "fabulous",
    "fantastic",
    "fun",
    "genius",
    "groundbreaking",
    "heavenly",
    "impressive",
    "innovative",
    "inventive",
    "kind",
    "legendary",
    "lifechanging",
    "lovely",
    "magical",
    "marvelous",
    "masterful",
    "miraculous",
    "original",
    "perfect",
    "phenomenal",
    "powerful",
    "remarkable",
    "rejuvenating",
    "resounding",
    "skillful",
    "stupendous",
    "stunning",
    "sweet",
    "terrific",
    "thoughtful",
    "thrilling",
    "wonderful",
		
        "When you hear the bell, come quickly."
        ]
    };


